config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions',
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "stories#index"
  get 'userindex' => 'searches#userindex'
  get 'maintitleindex' => 'searches#maintitleindex'
  get 'genreindex' => 'searches#genreindex'
  get 'order_popularity' => 'searches#order_popularity'
  get 'order_unpopular' => 'searches#order_unpopular'
  get 'order_favorite' => 'searches#order_favorite'
  get 'order_unfavorite' => 'searches#order_unfavorite'
  get 'order_post' => 'searches#order_post'
  get 'order_unpost' => 'searches#order_unpost'
  get 'order_comment' => 'searches#order_comment'
  get 'order_uncomment' => 'searches#order_uncomment'
  get 'maintitles/fav/:id' => 'maintitles#fav', as: "fav_maintitles"
  get 'q_and_a' => 'informations#q_and_a'
  resources :maintitles do
    get 'post_list' => 'users#post_list'
    post 'like' => 'favorites#create'
    delete 'unlike' => 'favorites#destroy'
    resources :stories do
      post 'like_review'
      post 'like_review_more'
      delete 'unlike_review'
      resources :comments, only: [:create,
                                  :destroy]
    end
  end
  resources :users do
    member do
      get 'mypagemain'
      get 'establishment'
      get 'user_post_list'
      get 'profile'
      get 'favorite_list'
    end
  end
  
end

app/models/maintitle.rb
class Maintitle < ApplicationRecord
  has_many :stories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :reviews, dependent: :destroy



  acts_as_taggable

  mount_uploader :cover, CoverUploader

  def favorited_by?(user) #いいねしているかどうか
    favorites.where(user_id: user.id).exists?
  end

  def reviewed_by?(user)
    reviews.where(user_id: user.id).exists?
  end

  validates :maintitle, presence: true
  validates :genre, presence: true

  enum genre:{"青春": 1,"恋愛": 2, "時代,歴史": 3, "ホラー": 4, "ファンタジー": 5, "推理": 6, "ライトノベル": 7, "自伝": 8, "その他": 9}

  

  
end

app/controllers/maintitles_controller.rb
class MaintitlesController < ApplicationController
  before_action :set_maintitle, only: [:edit,
                                       :update,
                                       :destroy
                                       ]

  def new
    @maintitle = Maintitle.new
  end

  def create
    @maintitle = Maintitle.new(maintitle_params)
    if @maintitle.save
      redirect_to new_maintitle_story_path(@maintitle[:id])
    else
      render 'maintitles/new'
    end
  end

  def edit
    #set_maintitle
  end

  def update
    #set_maintitle
    if @maintitle.user_id == current_user.id
      @maintitle.update(maintitle_params)
      redirect_to maintitle_post_list_path(@maintitle)
    else
      render 'maintitles/edit'
    end
  end

  def destroy
    #set_maintitle
    if @maintitle.user_id == current_user.id  
      @maintitle.destroy
    else
      render 'maintitles/edit'
    end
  end

  def fav
    maintitle = Maintitle.find(params[:id])
    if maintitle.favorited_by?(current_user)
      fav = current_user.favorites.find_by(maintitle_id: maintitle.id)
      fav.destroy
      @all_favorite = maintitle.all_favorite
      @sum = @all_favorite - 1
      maintitle.update(all_favorite: @sum)
      render json: maintitle.id
    else
      fav = current_user.favorites.new(maintitle_id: maintitle.id)
      fav.save
      @all_favorite = maintitle.all_favorite
      @sum = @all_favorite + 1
      maintitle.update(all_favorite: @sum)
      render json: maintitle.id
    end
  end



  private

  def maintitle_params
    params.require(:maintitle).permit(
      :maintitle,
      :genre,
      :explanation,
      :tag_list,
      :cover,
      :remove_cover).merge(user_id: current_user.id, all_review: 0, all_favorite: 0, all_comment: 0, all_story: 0)
  end

  def set_maintitle
    @maintitle = Maintitle.find(params[:id])
  end
end

app/helpers/maintitles_helper.rb
module MaintitlesHelper
end

app/views/maintitles/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <%=link_to root_path, class: "destroy_btn" do%>
        ホーム画面に戻る
      <%end%>
      <%=link_to mypagemain_user_path(current_user), class: "destory_btn" do%>
        マイページに戻る
      <%end%>
    </div>
  </div>

app/views/maintitles/edit.html.erb
<div class="wrapper">
  <div class="maintitle_new_title_contents">
    <h1 class="maintitle_new_title_content"><%=safe_join(@maintitle.maintitle.split("\n"),tag(:br))%><br />を編集する</h1>
  </div>
  <div class="maintitle_new_container">
    <div class="maintitle_new_main_contents">
      <div class="maintitle_delete_area">
        <%=link_to maintitle_path, method: :delete, data: {confirm: "#{@maintitle.maintitle}を削除しますか？"}, class: :maintitle_delete_btn do%>
          削除する
        <%end%>
      </div>
      <%=form_with model: @maintitle, local:true do |f|%>
      <div class="field">
          <p class="hissu">必須</p>
          <%=f.label :ジャンル, class: :story_new_explanation %><br />
          <%=f.select :genre, Maintitle.genres.keys, {:prompt => "---"} %>
        </div>
        <div class="field">
          <p class="hissu">必須</p>
          <%=f.label :タイトル, class: :story_new_explanation %><br />
          <%=f.text_area :maintitle, class: 'input_story_new_form' %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :tag_list, "タグをカンマ(小文字)区切りで入力" %><br />
          <%=f.text_field :tag_list, value: @maintitle.tag_list.join(','), "data-role" => "tagsinput", class: "form-control" %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :cover, class: :story_new_explanation do%>表紙をアップロード<br />
            <%=fa_icon "camera-retro", class: "input_my_image_icon" %>
            <%=f.file_field :cover, class: 'input_story_file_btn' %>
          <%end%>
          <p class="input_story_file_explanation">
            👈クリック
          </p>
          <div class="story_file_view_area">
            <%if @maintitle.cover?%>
              <%=image_tag @maintitle.cover.to_s, class: :story_file_view_image%>
            <%else%>
              <%=image_tag "no_image3.png", class: :story_file_view_image%>
            <%end%>
          </div>
          <p><%=f.check_box :remove_cover, id: :story_new_image_delete_btn%>　登録画像を削除</p>
        </div>
        <div class="field">
          <p class="ninni">任意</p>
          <%=f.label :小説の説明, class: :story_new_explanation %><br />
          <%=f.text_area :explanation, rows: 4, class: 'input_story_new_form' %>
        </div>
        
        <%=f.submit "変更する", class: 'btn btn-primary'%>
      <%end%>
    </div>
    <div class="maintitle_new_side_menu">
      <%=render 'shared/side_menu'%>
    </div>
  </div>
</div>

app/views/maintitles/new.html.erb
<div class="wrapper">
  <div class="maintitle_new_title_contents">
    <h1 class="maintitle_new_title_content">小説名を登録する</h1>
  </div>
  <div class="maintitle_new_container">
    <div class="maintitle_new_main_contents">
      <%=form_with model: @maintitle, local:true do |f|%>
      <div class="field">
          <p class="hissu">必須</p>
          <%=f.label :ジャンル, class: :story_new_explanation %><br />
          <%=f.select :genre, Maintitle.genres.keys, {:prompt => "---"} %>
        </div>
        <div class="field">
          <p class="hissu">必須</p>
          <%=f.label :小説名, class: :story_new_explanation %><br />
          <%=f.text_area :maintitle, class: 'input_story_new_form' %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :tag_list, "タグをカンマ(小文字)区切りで入力" %><br />
          <%=f.text_field :tag_list, value: @maintitle.tag_list.join(','), "data-role" => "tagsinput", class: "form-control" %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :cover, class: :story_new_explanation do%>表紙をアップロード<br />
            <%=fa_icon "camera-retro", class: "input_my_image_icon" %>
            <%=f.file_field :cover, class: 'input_story_file_btn' %>
          <%end%>
          <p class="input_story_file_explanation">
            👈クリック
          </p>
          
          <div class="story_file_view_area">
            <%=image_tag "no_image3.png", class: :story_file_view_image%>
          </div>
          <p><%=f.check_box :remove_cover, id: :story_new_image_delete_btn%>　登録画像を削除</p>
        </div>
        <div class="field">
          <p class="ninni">任意</p>
          <%=f.label :小説の説明, class: :story_new_explanation %><br />
          <%=f.text_area :explanation, rows: 4, class: 'input_story_new_form' %>
        </div>
        
        <%=f.submit "登録する", class: 'btn btn-primary'%>
      <%end%>
    </div>
    <div class="maintitle_new_side_menu">
      <%=render 'shared/side_menu'%>
    </div>
  </div>
</div>