config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions',
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "stories#index"
  get 'userindex' => 'searches#userindex'
  get 'maintitleindex' => 'searches#maintitleindex'
  get 'genreindex' => 'searches#genreindex'
  get 'order_popularity' => 'searches#order_popularity'
  get 'order_unpopular' => 'searches#order_unpopular'
  get 'order_favorite' => 'searches#order_favorite'
  get 'order_unfavorite' => 'searches#order_unfavorite'
  get 'order_post' => 'searches#order_post'
  get 'order_unpost' => 'searches#order_unpost'
  get 'order_comment' => 'searches#order_comment'
  get 'order_uncomment' => 'searches#order_uncomment'
  get 'maintitles/fav/:id' => 'maintitles#fav', as: "fav_maintitles"
  get 'q_and_a' => 'informations#q_and_a'
  resources :maintitles do
    get 'post_list' => 'users#post_list'
    post 'like' => 'favorites#create'
    delete 'unlike' => 'favorites#destroy'
    resources :stories do
      post 'like_review'
      post 'like_review_more'
      delete 'unlike_review'
      resources :comments, only: [:create,
                                  :destroy]
    end
  end
  resources :users do
    member do
      get 'mypagemain'
      get 'establishment'
      get 'user_post_list'
      get 'profile'
      get 'favorite_list'
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
        #  :confirmable,
         :omniauthable,omniauth_providers: %i[facebook google_oauth2]
  has_many :stories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :maintitles, dependent: :destroy
  has_many :maintitles, through: :favorites
  has_many :reviews, dependent: :destroy
  # has_many :favorite_maintitles, through: :favorites, source: :maintitle
  
  mount_uploader :my_image, MyImageUploader

  validates :nickname, presence: true

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    # binding.pry

    if snscredential.present? #sns登録のみ完了してるユーザー
      user = User.where(id: snscredential.user_id).first
      unless user.present? #ユーザーが存在しないなら
        user = User.new(
          # snsの情報
          # binding.pry # => auth.infoとかで確認 
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential
      #binding.pry

    else #sns登録 未
      user = User.where(email: auth.info.email).first
      if user.present? #会員登録 済
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else #会員登録 未
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        # binding.pry
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
        # binding.pry 
      end
    end
    # binding.pry
    # hashでsnsのidを返り値として保持しておく
    return { user: user , sns_id: sns.id }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  def facebook
    callback_for(:facebook) #コールバック
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    @omniauth = (request.env["omniauth.auth"])
    # binding.pry
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    # binding.pry
    if @user.persisted? #userが存在したら
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      # redirect_to root_path
    else #userが存在しなかったら
      session["devise.sns_id"] = sns_id #sns_credentialのid devise.他のアクションに持ち越せる(少し難)
      render template: "devise/registrations/new" #redirect_to だと更新してしまうのでrenderで
      # redirect_to root_path
    end
  end

  def failure
    redirect_to root_path and return
  end
  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def after_update_path_for(resource)
    mypagemain_user_path(resource)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  def create
    #binding.pry
     if params[:user][:password] == "" #sns登録なら
       params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
       params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
       super
       # binding.pry
       sns = SnsCredential.update(user_id:  @user.id)
     else #email登録なら
       # binding.pry
       super
     end
   end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:user_post_list,
                                  :mypagemain,
                                  :establishment,
                                  :profile,
                                  :favorite_list]
  before_action :set_user_all_review, only: [:mypagemain,
                                             :profile]

  def post_list #投稿一覧
    @stories = Story.where(maintitle_id: params[:maintitle_id]).order("created_at DESC").page(params[:page]).per(5)
    @maintitle = Maintitle.find(params[:maintitle_id])
    @user_id = @maintitle.user_id
    @user = User.find(@user_id)
    gon.maintitle_id = @maintitle.id
    gon.all_favorite = @maintitle.all_favorite
    
  end

  def user_post_list #未ログイン投稿一覧画
    #set_user
    
    @stories = Story.where(user_id: params[:id]).order("created_at DESC").page(params[:page]).per(10)
    @maintitles = Maintitle.where(user_id: params[:id])
    @reviews = Review.where(story_id: @stories.ids)
    if @reviews.present?
      @a = []
      @reviews.each do |review|
        p = review.review
        @a.push(p)
      end
      @user_all_review = @a.sum
    end
  end
  
  def mypagemain #マイページ
    # set_user
    # set_user_all_review
    @maintitles = Maintitle.where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
    @stories = Story.where(user_id: current_user.id).order("created_at DESC").page(params[:page]).per(5)
    
  end

  def establishment #開設一覧
    #set_user
    @maintitles = Maintitle.where(user_id: params[:id]).order("created_at DESC").page(params[:page]).per(10)
    @stories = Story.where(user_id: params[:id]).order("created_at DESC").page(params[:page]).per(3)
  end

  def profile #未ログイン時、他のユーザープロフィール画面
    #set_user
    @maintitles = Maintitle.where(user_id: params[:id]).order("created_at DESC").page(params[:page]).per(5)
    @stories = Story.where(user_id: params[:id]).order("created_at DESC").page(params[:page]).per(5)
    
  end

  def favorite_list
    @favorites = Favorite.where(user_id: @user.id)
    @a = []
    @favorites.each do |favorite|
      p = favorite.maintitle_id
      @a.push(p)
    end
    @maintitles = Maintitle.where(id: @a).order("created_at DESC").page(params[:page]).per(10)
    
  end
  


  private

  def set_user
    @user = User.find(params[:id])
  end
  
  def set_user_all_review
    @stories_review = Story.where(user_id: params[:id])
    @stories_review = Review.where(story_id: @stories_review.ids)
    if @stories_review.present?
      @a = []
      @stories_review.each do |review|
        p = review.review
        @a.push(p)
      end
      @user_all_review = @a.sum
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/establishment.html.erb
<div class="wrapper">
  <div class="esta_title_area">
    <h1 class="esta_title"><%=@user.nickname%>さんの小説一覧</h1>
  </div>
  
  <div class="esta_container">
    <div class="esta_main_contents">
      <div class="new_esta_list">
        小説一覧
      </div>
      <%@maintitles.each do |maintitle|%>
        <%=link_to maintitle_post_list_path(maintitle), class: :mystory_titles do%>
          <div class="mystory_novels_area">
            <div class="mystory_novels_cover_area">
              <%if maintitle.cover.present?%>
                <%=image_tag maintitle.cover.to_s, class: :mystory_novel_cover%>
              <%else%>
                <%=image_tag "no_image3.png", class: :mystory_novel_cover%>
              <%end%>
            </div>
            <div class="mystory_maintitle_explanation_area">
              <div class="mystory_maintitle_explanation">
              小説名　：
                <div class="mystory_maintitle">
                  <div class="mystory_title">
                    <%=safe_join(maintitle.maintitle.split("\n"),tag(:br))%>
                  </div>
                </div>
              </div>
              <div class="mystory_title_genres_explanation">
                ジャンル：
                <div class="mystory_title_genres">
                  <%=maintitle.genre%>
                </div>
              </div>
              <div class="mypage_maintitle_tags_explanation">
                タグ　　：
                <div class="mypage_maintitle_tags">
                  <%=render 'shared/mypage_tag_list', tag_list: maintitle.tag_list%>
                </div>
              </div>
              
              <div class="mystory_upload_time_explanation">
                作成日　：
                <div class="mystory_upload_time">
                  <%=maintitle.created_at.strftime('%Y/%m/%d')%>
                </div>
              </div>
              <div class="mystory_maintitle_review_explanation">
                <i class="fa fa-thumbs-o-up">
                </i>
                
                <%=maintitle.all_review%>
                　
                <i class="fa fa-heart-o">
                </i>
                <%=maintitle.all_favorite%>
                　
                <i class="fa fa-commenting-o ">
                </i>
                <%=maintitle.all_comment%>
                
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
      <div class="mypage_paginate">
        <%=paginate(@maintitles)%>
      </div>
    </div>
    <%if user_signed_in?%>
      <%if @user != current_user%>
        <%=render 'shared/not_current_side_menu'%>
      <%elsif @user == current_user%>
        <%=render 'shared/side_menu'%>
      <%end%>
    <%else%>
      <%=render 'shared/user_profile_side_menu'%>
    <%end%>
  </div>
</div>

app/views/users/mypagemain.html.erb
<div class="wrapper">
  <div class="mypagemain_title_area">
    <h1 class="mypagemain_title">マイページ</h1>
  </div>
  <div class="mypagemain_container">
    <div class="mypagemain_main_contents">
      <div class="mypagemain_user_profile_area">
        <div class="mypagemain_user_image_area">
          <%if @user.my_image?%>
            <%=image_tag @user.my_image.to_s, class: :user_image%>
          <%else%>
            <%=image_tag "no_avatar.png", class: :user_image%>
          <%end%>
        </div>
        <div class="mypagemain_user_nickname">
          <%=safe_join(@user.nickname.split("\n"),tag(:br))%>
          
          <div class="mypagemain_user_all_review_area">
            <div class="fa fa-thumbs-o-up">
            </div>
            
            <%if @user_all_review.present?%>
              <%=@user_all_review%>
            <%else%>
              0
            <%end%>
          </div>
          
        </div>
        <div class="mypagemain_user_profile">
          <%=safe_join(@user.profile_text.split("\n"),tag(:br))%>
        </div>
      </div>
      <div class="establishment_list_title">
        小説一覧
      </div>
      <%@maintitles.each do |maintitle|%>
        <%=link_to maintitle_post_list_path(maintitle), class: :mystory_titles do%>
          <div class="mystory_novels_area">
            <div class="mystory_novels_cover_area">
              <%if maintitle.cover.present?%>
                <%=image_tag maintitle.cover.to_s, class: :mystory_novel_cover%>
              <%else%>
                <%=image_tag "no_image3.png", class: :mystory_novel_cover%>
              <%end%>
            </div>
            <div class="mystory_maintitle_explanation_area">
              <div class="mystory_maintitle_explanation">
              小説名　：
                <div class="mystory_maintitle">
                  
                    <div class="mystory_title">
                      <%=safe_join(maintitle.maintitle.split("\n"),tag(:br))%>
                    </div>
                  
                </div>
              </div>
              <div class="mystory_title_genres_explanation">
                ジャンル：
                <div class="mystory_title_genres">
                  <%=maintitle.genre%>
                </div>
              </div>
              <div class="mypage_maintitle_tags_explanation">
                タグ　　：
                <div class="mypage_maintitle_tags">
                  <%=render 'shared/mypage_tag_list', tag_list: maintitle.tag_list%>
                </div>
              </div>
              
              <div class="mystory_upload_time_explanation">
                作成日　：
                <div class="mystory_upload_time">
                  <%=maintitle.created_at.strftime('%Y/%m/%d')%>
                </div>
              </div>
              <div class="mystory_maintitle_review_explanation">
                <i class="fa fa-thumbs-o-up">
                </i>
                
                <%=maintitle.all_review%>
                　
                <i class="fa fa-heart-o">
                </i>
                <%=maintitle.all_favorite%>
                
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
      <div class="mystory_maintitle_more">
        <%=link_to establishment_user_path(current_user), class: :mystory_maintitle_more_btn do%>
          小説一覧ページへ
        <%end%>
      </div>
      <div class="article_list_title">
        最近の投稿
      </div>
      <%@stories.each do |story|%>
        <%@maintitle = story.maintitle%>
        <%=link_to maintitle_story_path(@maintitle, story), class: :mystory_title do%>
          <div class="mystory_titles_area">
            <div class="mystory_novels_cover_area">
              <%if story.image.present?%>
                <%=image_tag story.image.to_s, class: :mystory_novel_cover%>
              <%else%>
                <%=image_tag "no_image3.png", class: :mystory_novel_cover%>
              <%end%>
            </div>
            <div class="mystory_story_title_area">
              <div class="mystory_titles_area_explanation">
                タイトル：
                
                <div class="mystory_titles">
                  
                    <%=safe_join(story.title.split("\n"),tag(:br))%>
                  
                </div>
              </div>
              <div class="mystory_title_tags_explanation">
                タグ　　：
                <div class="mystory_title_tags">
                  <%if story.tag_list.present?%>
                    <%=render 'shared/mypage_tag_list', tag_list: story.tag_list%>
                  <%end%>
                </div>
              </div>
              <div class="mystory_story_maintitle_explanation">
              小説名　：
                <div class="mystory_maintitle_name">
                  <%=safe_join(@maintitle.maintitle.split("\n"),tag(:br))%>
                </div>
              </div>
              <div class="mystory_maintitle_genre_explanation">
                ジャンル：
                <div class="mystory_maintitle_genre">
                  <%=@maintitle.genre%>
                </div>
              </div>
              <div class="mystory_upload_time_explanation">
                投稿日　：
                <div class="mystory_upload_time">
                  <%=story.created_at.strftime('%Y/%m/%d %H:%M')%>
                </div>
              </div>
              <div class="profile_story_review_explanation">
                <i class="fa fa-thumbs-o-up">
                </i>
              
                <%if story.reviews.present?%>
                  <%@a = []%>
                  <%story.reviews.each do |story|%>
                    <%p = story.review%>
                    <%@a.push(p)%>
                  <%end%>
                  <%story_review_count = @a.sum%>
                  <%=story_review_count%>
                <%else%>
                  0
                <%end%>
                　
                <i class="fa fa-commenting-o "></i>
                <%if story.comments.present?%>
                  <%=story.comments.count%>
                <%else%>
                  0
                <%end%>
                
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
      <div class="mypagemain_story_more_area">
        <%=link_to user_post_list_user_path(current_user), class: :mypagemain_story_more do%>
          投稿一覧ページへ
        <%end%>
      </div>
    </div>
    <%=render 'shared/mypage_side_menu'%>
  </div>
</div>

app/views/users/mypagemainsub.html.erb
<div class="wrapper">
  <div class="mypagemain_title_area">
    <h1 class="mypagemain_title"><%=@maintitle.maintitle%>　の投稿一覧</h1>
  </div>
  
  <div class="story_container">
    <div class="story_main_contents">
      <div class="story_new_edit_area">
        <div class="story_new_btn_area">
          <%=link_to new_maintitle_story_path(@maintitle[:id]), class: :story_new_btn do%>
            記事の投稿
          <%end%>
        </div>
        <div class="story_edit_btn_area">
          <%=link_to edit_maintitle_path(@maintitle[:id]), class: :story_edit_btn do%>
            開設の編集、削除
          <%end%>
        </div>
      </div>
      <%@stories.each do |story|%>
        <div class="story_titles_area">
          <%=link_to maintitle_story_path(@maintitle, story), class: :mystory_titles do%>
            <div class="story_title">
            ○　<%=story.title%>
            </div>
          <%end%>
          <div class="tags_and_time_area">
            <div class="story_title_tags">
              <%=render 'shared/mypage_tag_list', tag_list: story.tag_list%>
            </div>
            <div class="story_upload_time">
              <%=story.created_at.strftime('%Y/%m/%d %H:%M')%>
            </div>
          </div>
        </div>
      <%end%>
      <div class="mypage_paginate">
        <%=paginate(@stories)%>
      </div>
    </div>
    <%=render 'shared/side_menu'%>
  </div>
</div>

app/views/users/post_list.html.erb
<div class="wrapper">
  <div class="mypagemain_title_area">
    <h1 class="mypagemain_title"><%=safe_join(@maintitle.maintitle.split("\n"),tag(:br))%></h1>
  </div>
  <div class="story_container">
    <div class="story_main_contents">
      <%if user_signed_in?%>
        <%if @user != current_user%>
          <div class="favorite_area">
            <% if !Favorite.exists?(user_id:current_user.id, maintitle_id: @maintitle.id) %>
              <%= link_to fav_maintitles_path(@maintitle), class: :favorite_btn, remote: :true, data: "#{@maintitle.all_favorite}" do%>
                <div class="like_area">
                  <div class="like", id="<%=@maintitle.id%>">
                    お気に入り
                  </div>
                </div>
              <%end%>
            <% else %>
              <%= link_to fav_maintitles_path(@maintitle), class: :favorite_btn, remote: :true do%>
                <div class="unlike_area">
                  <div class="unlike", id="<%=@maintitle.id%>">
                    お気に入り解除
                  </div>
                </div>
              <%end%>
            <%end%>
          </div>
        <%end%>
      <%end%>
      <%if @maintitle.cover.present?%>
        <div class="posli_cover_area">
          <%=image_tag @maintitle.cover.to_s, class: :posli_cover%>
        </div>
      <%end%>
      <div class="posli_story_user_time_genre_area">
        <div class="posli_user_nickname_image_area">
          <div class="posli_story_user_nickname">
            著者　　：
              <%=link_to profile_user_path(@user), class: :posli_story_user_nickname_link do%>
                <%=@user.nickname%>
              <%end%>
          </div>
          <div class="posli_story_user_image">
            <%if @user.my_image.present?%>
              <%=image_tag @user.my_image.to_s, class: :posli_story_user_image_icon%>
            <%else%>
              <%=image_tag "no_avatar.png", class: :posli_story_user_image_icon%>
            <%end%>
          </div>
        </div>
        <div class="posli_maintitle_time">
          作成日：　<%=@maintitle.created_at.strftime('%Y/%m/%d')%>
        </div>
        <div class="posli_maintitle_genre_explanation">
          ジャンル：
          <div class="posli_maintitle_genre">
            <%=@maintitle.genre%>
          </div>
        </div>
        <div class="posli_tag_explanation">
          タグ　　：
          <div class="posli_tag">
            <%=render 'shared/posli_tag_list', tag_list: @maintitle.tag_list%>
          </div>
        </div>
        <div class="posli_review_icon">
          <i class="fa fa-thumbs-o-up ">
          </i> 
          <%=@maintitle.all_review%>
          　
          <i class="fa fa-heart-o ">
          </i> 
          <i class="posli_all_favorite">
            <%=@maintitle.all_favorite%>
          </i>
          　
          <i class="fa fa-commenting-o ">
          </i>
          <%if @maintitle.all_comment.present?%>
            <%=@maintitle.all_comment%>
          <%else%>
            0
          <%end%>
        </div>
      </div>
        小説の概要
      <div class="posli_maintitle_explanation_area">
        <%if @maintitle.explanation?%>
          <%=safe_join(@maintitle.explanation.split("\n"),tag(:br))%>
        <%else%>
          未登録
        <%end%>
      </div>
      <%if user_signed_in?%>
        <%if @user == current_user%>
          <div class="posli_story_new_edit_area">
            <div class="posli_story_new_btn_area">
              <%=link_to new_maintitle_story_path(@maintitle), class: :posli_story_new_btn do%>
                続きの話を書く
              <%end%>
            </div>
            <div class="posli_story_edit_btn_area">
              <%=link_to edit_maintitle_path(@maintitle), class: :posli_story_edit_btn do%>
                小説の情報を編集する
              <%end%>
            </div>
          </div>
        <%end%>
      <%end%>
      <div class="posli_story_list_explanation_area">
        <h1 class="posli_story_list_explanation">
          投稿一覧
        </h1>
      </div>
      <%@stories.each do |story|%>
        <%@maintitle = story.maintitle%>
        <%=link_to maintitle_story_path(@maintitle, story), class: :mystory_title do%>
          <div class="mystory_titles_area">
            <div class="mystory_novels_cover_area">
              <%if story.image.present?%>
                <%=image_tag story.image.to_s, class: :mystory_novel_cover%>
              <%else%>
                <%=image_tag "no_image3.png", class: :mystory_novel_cover%>
              <%end%>
            </div>
            <div class="mystory_story_title_area">
              <div class="mystory_titles_area_explanation">
                タイトル：
                <div class="mystory_titles">
                  <%=safe_join(story.title.split("\n"),tag(:br))%>
                </div>
              </div>
              <div class="mystory_title_tags_explanation">
                タグ　　：
                <div class="mystory_title_tags">
                  <%if story.tag_list.present?%>
                    <%=render 'shared/mypage_tag_list', tag_list: story.tag_list%>
                  <%end%>
                </div>
              </div>
              
              <div class="mystory_upload_time_explanation">
                投稿日　：
                <div class="mystory_upload_time">
                  <%=story.created_at.strftime('%Y/%m/%d %H:%M')%>
                </div>
              </div>
              <div class="mystory_all_review">
                <i class="fa fa-thumbs-o-up">
                </i>
                <%if story.reviews.present?%>
                  <%@a = []%>
                  <%story.reviews.each do |story_review|%>
                    <%p = story_review.review%>
                    <%@a.push(p)%>
                  <%end%>
                  <%story_all_review = @a.sum%>
                    <%=story_all_review%>
                <%else%>
                    0
                <%end%>
                　
                <i class="fa fa-commenting-o "></i>
                <%if story.comments.present?%>
                  <%=story.comments.count%>
                <%else%>
                  0
                <%end%>
                
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
      <div class="mypage_paginate">
        <%=paginate(@stories)%>
      </div>
    </div>
    <%if user_signed_in?%>
      <%if @user != current_user%>
        <%=render 'shared/not_current_side_menu'%>
      <%elsif @user == current_user%>
        <%=render 'shared/side_menu'%>
      <%end%>
    <%else%>
      <%=render 'shared/user_profile_side_menu'%>
    <%end%>
  </div>
</div>