config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions',
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "stories#index"
  get 'userindex' => 'searches#userindex'
  get 'maintitleindex' => 'searches#maintitleindex'
  get 'genreindex' => 'searches#genreindex'
  get 'order_popularity' => 'searches#order_popularity'
  get 'order_unpopular' => 'searches#order_unpopular'
  get 'order_favorite' => 'searches#order_favorite'
  get 'order_unfavorite' => 'searches#order_unfavorite'
  get 'order_post' => 'searches#order_post'
  get 'order_unpost' => 'searches#order_unpost'
  get 'order_comment' => 'searches#order_comment'
  get 'order_uncomment' => 'searches#order_uncomment'
  get 'maintitles/fav/:id' => 'maintitles#fav', as: "fav_maintitles"
  get 'q_and_a' => 'informations#q_and_a'
  resources :maintitles do
    get 'post_list' => 'users#post_list'
    post 'like' => 'favorites#create'
    delete 'unlike' => 'favorites#destroy'
    resources :stories do
      post 'like_review'
      post 'like_review_more'
      delete 'unlike_review'
      resources :comments, only: [:create,
                                  :destroy]
    end
  end
  resources :users do
    member do
      get 'mypagemain'
      get 'establishment'
      get 'user_post_list'
      get 'profile'
      get 'favorite_list'
    end
  end
  
end

app/views/shared/_footer.html.erb
<footer>
  <div class="sitename">
    <%=link_to root_path, class: "sitetitle" do%>
      <%=image_tag "waku.png", class: "sitetitle_logo" %>
    <% end %>
  </div>
  <span class="copyright"> © 2019 WakuwakuStory</span>
</footer>

app/views/shared/_genre_dropdwn_menu.html.erb
<ul class="genre_dropdwn_menu">
  <li id="genre_area">
    <%=fa_icon 'search'%>ジャンル
    <ul>
      <%=link_to genreindex_path(search: "青春"), class: :dropdwn_genre_list  do%>
      <li>
        
          青春
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "恋愛"), class: :dropdwn_genre_list do%>
      <li>
        
          恋愛
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "時代,歴史"), class: :dropdwn_genre_list  do%>
      <li>
        
          時代,歴史
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "ホラー"), class: :dropdwn_genre_list  do%>
      <li>
        
          ホラー
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "ファンタジー"), class: :dropdwn_genre_list  do%>
      <li>
        
          ファンタジー
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "推理"), class: :dropdwn_genre_list  do%>
      <li>
        
          推理
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "ライトノベル"), class: :dropdwn_genre_list  do%>
      <li>
        
          ライトノベル
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "自伝"), class: :dropdwn_genre_list  do%>
      <li>
        
          自伝
        
      </li>
      <%end%>
      <%=link_to genreindex_path(search: "その他"), class: :dropdwn_genre_list  do%>
      <li>
        
          その他
        
      </li>
      <%end%>
    </ul>
  </li>
</ul>

app/views/shared/_header.html.erb
<div class="wrapper">
  <header id="main_header">
    <div class="sitename">
      <%=link_to root_path, class: "sitetitle" do%>
        <%=image_tag "waku.png", class: "sitetitle_logo" %>
      <% end %>
    </div>
    <div class="q_and_a_link">
      <%=link_to q_and_a_path, class: :q_and_a_link_btn do%>
        このサービスについて（Q&A）
      <%end%>
    </div>
    
  </header>
</div>

app/views/shared/_header_signup_space.html.erb
<div class="wrapper">
  <div class="btn_space">
  <%if user_signed_in?%>
    <%=link_to mypagemain_user_path(current_user), class: :sign_up_current_user_icon do%>
      <div class="header_btn_left_content">
        <p class="current_user_nickname">
          <%=safe_join(current_user.nickname.split("\n"),tag(:br))%>
        </p>
        <div class="header_my_image_area">
          <% if current_user.persisted? && current_user.my_image? %>
            <%=image_tag current_user.my_image.to_s, class: :header_my_image_icon%>
          <%else%>
            <%=image_tag "no_avatar.png", class: :header_my_image_icon%>
          <%end%>
        </div>
      </div>
    <%end%>
    <div class="header_seach_area">
      <div class="dropdwn_search_area">
        <%=render 'shared/genre_dropdwn_menu'%>
      </div>
      <div class="dropdwn_search_area">
        <%=render 'shared/order_dropdwn_menu'%>
      </div>

      <div class="title_search_area">
        <%=form_tag userindex_path, method: :get, class: :title_search_form_area do %>
          <%=text_field_tag :search, "", class: :title_search_form, placeholder: '著者' %>
          <%=button_tag type: "submit", class: :title_search_btn do %>
            <%=fa_icon 'search' %>
          <%end %>
        <%end %>
      </div>
      <div class="title_search_area">
        <%=form_tag maintitleindex_path, method: :get, class: :title_search_form_area do %>
          <%=text_field_tag :search_title, "", class: :title_search_form, placeholder: '小説名' %>
          <%=button_tag type: "submit", class: :title_search_btn do %>
            <%=fa_icon 'search' %>
          <%end %>
        <%end %>
      </div>
    </div>
    <div class="header_btn_right_content">
      <ul class="right_content_btns">
        <%=link_to root_path, class: "sign_btn" do%>
          <li id="right_content_btn">
            トップページ
          </li>
        <%end%>
        <%=link_to mypagemain_user_path(current_user), class: "sign_btn" do%>
          <li id="right_content_btn">
            マイページ
          </li>
        <%end%>
        <%=link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "sign_btn" do%>
          <li id="right_content_btn">
            ログアウト
          </li>
        <%end%>
        
      </ul>
    </div>
  <%else%>
    <div class="header_btn_left_content">
      <p class="current_user_nickname">
        こんにちはゲストさん
      </p>
      <div class="header_my_image_area">
        <%=image_tag "no_avatar.png", class: :header_my_image_icon%>
      </div>
    </div>
    <div class="header_seach_area">
      <div class="dropdwn_search_area">
        <%=render 'shared/genre_dropdwn_menu'%>
      </div>
      <div class="dropdwn_search_area">
        <%=render 'shared/order_dropdwn_menu'%>
      </div>
      <div class="title_search_area">
        <%=form_tag userindex_path, method: :get, class: :title_search_form_area do %>
          <%=text_field_tag :search, "", class: :title_search_form, placeholder: "著者" %>
          <%=button_tag type: "submit", class: :title_search_btn do %>
            <%=fa_icon 'search' %>
          <%end %>
        <%end %>
      </div>
      <div class="title_search_area">
        <%=form_tag maintitleindex_path, method: :get, class: :title_search_form_area do %>
          <%=text_field_tag :search_title, "", class: :title_search_form, placeholder: '小説名' %>
          <%=button_tag type: "submit", class: :title_search_btn do %>
            <%=fa_icon 'search' %>
          <%end %>
        <%end %>
      </div>
    </div>
    <div class="header_btn_right_content">
      <ul class="right_content_btns"> 
        <%=link_to root_path, class: "sign_btn" do %>
          <li id="right_content_btn">
            トップページ
          </li>
        <%end%>
        <%=link_to new_user_registration_path, class: "sign_btn" do%>
          <li id="right_content_btn">
            新規登録
          </li>
        <%end%>
        <%=link_to new_user_session_path, class: "sign_btn" do %>
          <li id="right_content_btn">
            ログイン
          </li>
        <%end%>
      </ul>
    </div>
  <%end%>
  </div>
</div>

app/views/shared/_maintitle_all_review_count.html.erb
<i class="all_count">
  <%=@story_review_count%>
</i>
  

app/views/shared/_mypage_side_menu.html.erb
<div class="mypagemain_side_contents">
  <%=link_to root_path, class: :side_menu_list do%>
    <div class="side_content_top">
      トップページ
    </div>
  <%end%>
  <%=link_to mypagemain_user_path(current_user), class: :side_menu_list do%>
    <div class="side_content">
      マイページ
    </div>
  <%end%>
  <%=link_to new_maintitle_path, class: :side_menu_list do%>
    <div class="side_content">
      新しく小説を書く
    </div>
  <%end%>
  <%=link_to establishment_user_path(current_user), class: :side_menu_list do%>
    <div class="side_content">
      小説一覧
    </div>
  <%end%>
  <%=link_to user_post_list_user_path(current_user), class: :side_menu_list do%>
    <div class="side_content">
      投稿一覧
    </div>
  <%end%>
  <%=link_to favorite_list_user_path(current_user), class: :side_menu_list do%>
    <div class="side_content">
      お気に入り一覧
    </div>
  <%end%>
  <%=link_to edit_user_registration_path, class: :side_menu_list do%>
    <div class="side_content">
      プロフィールを編集する
    </div>
  <%end%>
  <%=link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: :side_menu_list do%>
    <div class="side_content">
      ログアウト
    </div>
  <%end%>
</div>

app/views/shared/_mypage_tag_list.html.erb
<% tag_list.each_with_index do |tag, i| %>
  <span class="label label-primary"><%= tag %></span>
  <%break if i == 3%>
<% end %>

app/views/shared/_not_current_side_menu.html.erb
<div class="profile_side_contents">
  <%=link_to establishment_user_path(@user), class: :side_menu_list do%>
    <div class="side_content_top">
      このユーザーの小説一覧
    </div>
  <%end%>
  <%=link_to user_post_list_user_path(@user), class: :side_menu_list do%>
    <div class="side_content">
      このユーザーの投稿一覧
    </div>
  <%end%>
  <div class="side_content_signup_area">
    <%=link_to root_path, class: :side_menu_list do%>
      <div class="side_content_top">
        トップページ
      </div>
    <%end%>
    <%=link_to mypagemain_user_path(current_user), class: :side_menu_list do%>
      <div class="side_content">
        マイページ
      </div>
    <%end%>
    <%=link_to favorite_list_user_path(current_user), class: :side_menu_list do%>
      <div class="side_content">
        お気に入りタイトル一覧
      </div>
    <%end%>
    <%=link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: :side_menu_list do%>
      <div class="side_content">
        ログアウト
      </div>
    <%end%>
  </div>
  
</div>

app/views/shared/_order_dropdwn_menu.html.erb
<ul class="order_dropdwn_menu">
  <li id="order_area">
    <i class="fa fa-sort-amount-asc "></i> 並び替え
    <ul>
      <%=link_to order_popularity_path(search: "評価が高い"), class: :dropdwn_order_list do%>
      <li>
        
          評価が高い
        
      </li>
      <%end%>
      <%=link_to order_unpopular_path(search: "評価が低い"), class: :dropdwn_order_list do%>
      <li>
        
          評価が低い
        
      </li>
      <%end%>
      <%=link_to order_favorite_path(search: "登録が多い"), class: :dropdwn_order_list  do%>
      <li>
        
          登録が多い
        
      </li>
      <%end%>
      <%=link_to order_unfavorite_path(search: "登録が少ない"), class: :dropdwn_order_list  do%>
      <li>
        
          登録が少ない
        
      </li>
      <%end%>
      <%=link_to order_post_path(search: "投稿が多い"), class: :dropdwn_order_list  do%>
      <li>
        
          投稿が多い
        
      </li>
      <%end%>
      <%=link_to order_unpost_path(search: "投稿が少ない"), class: :dropdwn_order_list  do%>
      <li>
        
          投稿が少ない
        
      </li>
      <%end%>
      <%=link_to order_comment_path(search: "コメントが多い"), class: :dropdwn_order_list  do%>
      <li>
        
          コメントが多い
        
      </li>
      <%end%>
      <%=link_to order_uncomment_path(search: "コメントが少ない"), class: :dropdwn_order_list  do%>
      <li>
        
          コメントが少ない
        
      </li>
      <%end%>
    </ul>
  </li>
</ul>

app/views/shared/_posli_tag_list.html.erb
<% tag_list.each_with_index do |tag| %>
  <span class="label label-primary"><%= tag %></span>
<% end %>

app/views/shared/_profile_side_menu.html.erb
<div class="profile_side_contents">
  <%=link_to root_path, class: :side_menu_list do%>
    <div class="side_content_top">
      トップページ
    </div>
  <%end%>
  <%=link_to new_user_registration_path, class: :side_menu_list do%>
    <div class="side_content">
      新規登録
    </div>
   <%end%>
   <%=link_to new_user_session_path, class: :side_menu_list do%>
    <div class="side_content">
      ログイン
    </div>
  <%end%>
</div>

app/views/shared/_search_side_menu.html.erb
<div class="mypagemain_side_contents">
  <div class="side_content_top">
    <%=link_to root_path, class: :side_menu_list do%>
      トップページ
    <%end%>
  </div>
  <div class="side_content">
    <%=link_to mypagemain_user_path(current_user), class: :side_menu_list do%>
      マイページ
    <%end%>
  </div>
  <div class="side_content">
    <%=link_to new_maintitle_path(current_user), class: :side_menu_list do%>
      新しく開設する
    <%end%>
  </div>
  <div class="side_content">
    <%=link_to establishment_user_path(current_user), class: :side_menu_list do%>
      開設一覧
    <%end%>
  </div>
  <div class="side_content">
    <%=link_to user_post_list_user_path(current_user), class: :side_menu_list do%>
      投稿一覧
    <%end%>
  </div>
  <div class="side_content">
    <%=link_to edit_user_registration_path, class: :side_menu_list do%>
      プロフィールを編集する
    <%end%>
  </div>
  <div class="side_content">
    <%=link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: :side_menu_list do%>
      ログアウト
    <%end%>
  </div>
</div>

app/views/shared/_side_menu.html.erb
<div class="mypagemain_side_contents">
  <%=link_to root_path, class: :side_menu_list do%>
    <div class="side_content_top">
      トップページ
    </div>
  <%end%>
  <%=link_to mypagemain_user_path(current_user), class: :side_menu_list do%>
    <div class="side_content">
      マイページ
    </div>
  <%end%>
  <%=link_to favorite_list_user_path(current_user), class: :side_menu_list do%>
    <div class="side_content">
      お気に入り一覧
    </div>
  <%end%>
  <%=link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: :side_menu_list do%>
    <div class="side_content">
      ログアウト
    </div>
  <%end%>
</div>

app/views/shared/_user_profile_side_menu.html.erb
<div class="profile_side_contents">
  <%=link_to establishment_user_path(@user), class: :side_menu_list do%>
    <div class="side_content_top">
      このユーザーの小説一覧
    </div>
  <%end%>
  <%=link_to user_post_list_user_path(@user), class: :side_menu_list do%>
    <div class="side_content">
      このユーザーの投稿一覧
    </div>
  <%end%>
  <div class="side_content_signup_area">
    <%=link_to new_user_registration_path, class: :side_menu_list do%>
      <div class="side_content_top">
        新規登録
      </div>
    <%end%>
    <%=link_to new_user_session_path, class: :side_menu_list do%>
      <div class="side_content">
        ログイン
      </div>
    <%end%>
    <%=link_to root_path, class: :side_menu_list do%>
      <div class="side_content">
        トップページ
      </div>
    <%end%>
  </div>
</div>