config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {   registrations: 'users/registrations',
                                      sessions: 'users/sessions',
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root "stories#index"
  get 'userindex' => 'searches#userindex'
  get 'maintitleindex' => 'searches#maintitleindex'
  get 'genreindex' => 'searches#genreindex'
  get 'order_popularity' => 'searches#order_popularity'
  get 'order_unpopular' => 'searches#order_unpopular'
  get 'order_favorite' => 'searches#order_favorite'
  get 'order_unfavorite' => 'searches#order_unfavorite'
  get 'order_post' => 'searches#order_post'
  get 'order_unpost' => 'searches#order_unpost'
  get 'order_comment' => 'searches#order_comment'
  get 'order_uncomment' => 'searches#order_uncomment'
  get 'maintitles/fav/:id' => 'maintitles#fav', as: "fav_maintitles"
  get 'q_and_a' => 'informations#q_and_a'
  resources :maintitles do
    get 'post_list' => 'users#post_list'
    post 'like' => 'favorites#create'
    delete 'unlike' => 'favorites#destroy'
    resources :stories do
      post 'like_review'
      post 'like_review_more'
      delete 'unlike_review'
      resources :comments, only: [:create,
                                  :destroy]
    end
  end
  resources :users do
    member do
      get 'mypagemain'
      get 'establishment'
      get 'user_post_list'
      get 'profile'
      get 'favorite_list'
    end
  end
  
end

app/models/story.rb
class Story < ApplicationRecord

  belongs_to :maintitle
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  acts_as_taggable

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :story, presence: true

  def previous
    maintitle.stories.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    maintitle.stories.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  
  before_action :set_maintitle, only: [:new,
                                       :create,
                                       :show,
                                       :edit,
                                       :update,
                                       :destroy,
                                       :like_review,
                                       :like_review_more,
                                       :unlike_review]
  before_action :set_story, only: [:show,
                                   :destroy,
                                   :edit,
                                   :update]

  def index
    @maintitles = Maintitle.all.order("created_at DESC").page(params[:page]).per(16)
    
  end

  def new
    #set_maintitle
    @story = Story.new
    
  end

  def create
    #set_maintitle
    @story = @maintitle.stories.new(story_params)
    if @story.save
      @story_count = @maintitle.all_story + 1
      @maintitle.update(new_story: @story.created_at, all_story: @story_count)
      redirect_to maintitle_story_path(@maintitle, @story)

      # flash[:success] = "記事を作成しました"
      # redirect_to articles_url
    else
      render 'stories/new'
    end
  end

  def show
    #set_maintitle
    #set_story
    @comment = Comment.new
    @comments = @story.comments.includes(:user).order("created_at DESC")
    gon.maintitle_id = @maintitle.id
    gon.story_id = @story.id
    @user = User.find(@story.user_id)
    if user_signed_in?
      @review = Review.find_by(story_id: @story.id, user_id: current_user.id)
      if @review != nil
        gon.my_review_count = @review.review + 1
      else
        @review = Review.create(user_id: current_user.id, story_id: @story.id, maintitle_id: @maintitle.id, review: 0)
        gon.my_review_count = @review.review + 1
      end
    end
    @reviews = Review.where(story_id: @story.id)
    @story_review_count = @reviews.sum(:review)
    
    gon.review_all_count = @story_review_count + 1
    
    @stories = @maintitle.stories.order('created_at desc, id desc')
    gon.story_comment_count = @story.comments.count
    # @story_next = @story_next_id.order("id DESC").first
    # @story_next = @story_next_id.where("id < ?", id).order("id DESC").first
  end

  def destroy
    #set_story
    #set_maintitle

    if @story.user_id == current_user.id
      @story_count = @maintitle.all_story.to_i - 1
      a = @story.reviews.sum(:review)
      b = @story.comments.count(:comment)
      @maintitle_comment_count = @maintitle.all_comment - b
      @maintitle_review_count = @maintitle.all_review - a
      @maintitle.update(all_story: @story_count, all_review: @maintitle_review_count, all_comment: @maintitle_comment_count)
      @story.destroy
      redirect_to maintitle_post_list_path(@maintitle)
    end
  end

  def edit
    #set_maintitle
    #set_story
  end

  def update
    #set_story
    if @story.user_id == current_user.id
      @story.update(story_params)
      redirect_to maintitle_story_path(@maintitle, @story)
    else
      # redirect_to 
    end
  end

  def like_review
    # set_maintitle
    @story = Story.find(params[:story_id])
    @review = Review.find_by(story_id: @story.id, user_id: current_user.id)
    p = @review.review + 1
    @review.update(review: p)
    @maintitle_review = @maintitle.reviews
    @sum = @maintitle_review.sum(:review)

    @maintitle.update(all_review: @sum)
    render json: @story.id


  end

  def unlike_review
    # set_maintitle
    @story = Story.find(params[:story_id])
    @review = Review.find_by(user_id: current_user.id, story_id: @story.id)
    @story_review = @review.review
    @maintitle_review = @maintitle.reviews
    @sum = @maintitle_review.sum(:review)
    @sum = @sum - @story_review
    @maintitle.update(all_review: @sum)
    @review.update(review: 0)
    
    render json: @story.id
    


  end

  


  private
  
  def story_params
    params.require(:story).permit(
      :title, 
      :story, 
      :tag_list,
      :image,
      :remove_image,
      :synopsis,
      :notice).merge(user_id: current_user.id)
  end

  def set_maintitle
    @maintitle = Maintitle.find(params[:maintitle_id])
  end

  def set_story
    @story = Story.find(params[:id])
  end

end

app/controllers/storys_controller.rb
class StorysController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @story = Story.new
  end

  def create

  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_tag_list.html.erb
<% tag_list.each do |tag| %>
  <span class="label label-primary"><%= tag %></span>
<% end %>

app/views/stories/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <%=link_to root_path, class: "destroy_btn" do%>
        ホーム画面に戻る
      <%end%>
      <%=link_to mypagemain_user_path, class: "destory_btn" do%>
        マイページに戻る
      <%end%>
    </div>
  </div>

app/views/stories/edit.html.erb
<div class="wrapper">
  <div class="story_new_title_contents">
    <h1 class="story_new_title_content">
      <%=safe_join(@story.title.split("\n"),tag(:br))%><br />を編集
    </h1>
  </div>
  <div class="story_new_container">
    <div class="story_new_main_contents">
      <%=form_with model: [@maintitle, @story], local:true do |f|%>
        <div class="field">
          <p class="hissu">必須</p>
          <%=f.label :タイトル, class: :story_new_explanation %><br />
          <%=f.text_area :title, class: 'input_story_new_form', value: @story.title %>
        </div>
        <div class="form-group">
        <p class="ninni">任意</p>
          <%=f.label :tag_list, "タグをカンマ(小文字)区切りで入力" %><br />
          <%=f.text_field :tag_list, value: @story.tag_list.join(','), "data-role" => "tagsinput", class: "form-control" %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :image, class: :story_new_explanation do%>画像アップロード（5MBまで）<br />
            <%=fa_icon "camera-retro", class: "input_my_image_icon" %>
            <%=f.file_field :image, class: 'input_story_file_btn' %>
          <%end%>
          <p class="input_story_file_explanation">
            👈クリック<br />　　横向きに表示されても投稿時には縦になります
          </p>
          <div class="story_file_view_area">
            <%if @story.image?%>
              <%=image_tag @story.image.to_s, class: :story_file_view_image%>
            <%else%>
              <%=image_tag "no_file2.jpeg", class: :story_file_view_image%>
            <%end%>
          </div>
          <p><%=f.check_box :remove_image, id: :story_new_image_delete_btn%>　登録画像を削除</p>
        </div>
        
        <div class="field form-group">
          <p class="ninni">任意</p>
          <%=f.label :前回のあらすじなど、自由に投稿, class: :story_new_explanation %><br />
          <%=f.text_area :synopsis, class: 'input_story_new_form' %>
        </div>
        <div class="field form-group">
          <p class="hissu">必須</p>
          <%=f.label :記事, class: :story_new_explanation %><br />
          <%=f.text_area :story, rows: 4, class: 'input_story_new_form', value: @story.story %>
        </div>
        <div class="field form-group">
          <p class="ninni">任意</p>
          <%=f.label :次回予告など、自由に投稿, class: :story_new_explanation %><br />
          <%=f.text_area :notice, class: 'input_story_new_form' %>
        </div>
        
        <%=f.submit "編集する", data: {confirm: "編集しますか？"}, class: 'btn btn-primary'%>
        
      <%end%>
    </div>
    <div class="story_new_side_menu">
      <%=render 'shared/side_menu'%>
    </div>
  </div>
</div>

app/views/stories/index.html.erb
<div class="wrapper">
  <div class="story_index_title_area", style="background-image: url(/images/index_image_3.jpg)">
    <h1 class="story_index_title">
      Wakuwaku Story
    </h1>
    <p class="story_index_subtitle">
      オリジナルをシェアしよう<br />WakuwakuStoryはオリジナルの小説をシェアできるサービスです
    </p>
    <%=link_to "https://www.pakutaso.com", title: "フリー写真素材ぱくたそ", class: :pakutaso do%>
      提供元：フリー写真素材ぱくたそ
    <%end%>
  </div>
  
  <div class="story_container">
    <div class="story_main_contents">
      <div class="new_article_list">
        小説一覧
      </div>
      <%@maintitles.each do |maintitle|%>
        <%=link_to maintitle_post_list_path(maintitle), class: :index_maintitle_image_path do%>
          <div class="index_story_titles_area">
            
              <div class="index_maintitle_image_area">
                <%if maintitle.cover.present?%>
                  <%=image_tag maintitle.cover.url, class: :index_maintitle_image%>
                <%else%>
                  <%=image_tag "no_image3.png", class: :index_maintitle_image%>
                <%end%>
              </div>
            
            <div class="index_maintitle_content">
              
              <div class="story_maintitle">
                  <%=safe_join(maintitle.maintitle.split("\n"),tag(:br))%>
              </div>
              <div class="story_genre">
                <%=maintitle.genre%>
              </div>
              <div class="story_user_name">
                <%user = User.find(maintitle.user_id)%>
                  <%=user.nickname%>
              </div>
              <div class="maintitle_all_review">
                <i class="fa fa-thumbs-o-up">
                </i>
                <%=maintitle.all_review%>
                　
                <i class="fa fa-heart-o ">
                </i> 
                <%=maintitle.all_favorite%>
              </div>
            </div>
          </div>
        <%end%>
      <%end%>
      <div class="index_paginate">
        <%=paginate(@maintitles)%>
      </div>
    </div>
    <%if user_signed_in?%>
      <%=render 'shared/side_menu'%>
    <%else%>
      <%=render 'shared/profile_side_menu'%>
    <%end%>
  </div>
  
</div>
     

app/views/stories/new.html.erb
<div class="wrapper">
  <div class="story_new_title_contents">
    <h1 class="story_new_title_content">
      <%=safe_join(@maintitle.maintitle.split("\n"),tag(:br))%><br />の話を登録する
    </h1>
  </div>
  <div class="story_new_container">
    <div class="story_new_main_contents">
      <%=form_with model: [@maintitle, @story], local:true do |f|%>
        <div class="field">
          <p class="hissu">必須</p>
          <%=f.label :タイトル, class: :story_new_explanation %><br />
          <%=f.text_area :title, placeholder: "例）〜第○章〜など", class: 'input_story_new_form' %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :tag_list, "タグをカンマ(小文字)区切りで入力" %><br />
          <%=f.text_field :tag_list, value: @story.tag_list.join(','), "data-role" => "tagsinput", class: "form-control" %>
        </div>
        <div class="form-group">
          <p class="ninni">任意</p>
          <%=f.label :image, class: :story_new_explanation do%>挿絵をアップロード（5MBまで）<br />
            <%=fa_icon "camera-retro", class: "input_my_image_icon" %>
            <%=f.file_field :image, class: 'input_story_file_btn' %>
          <%end%>
          <p class="input_story_file_explanation">
            👈クリック<br />　　※横向きに表示されても投稿時には縦になります
          </p>
          <div class="story_file_view_area">
            <%=image_tag "no_image3.png", class: :story_file_view_image%>
          </div>
          <p><%=f.check_box :remove_image, id: :story_new_image_delete_btn%>　登録画像を削除</p>
        </div>
        <div class="field form-group">
          <p class="ninni">任意</p>
          <%=f.label :前回のあらすじなど、自由に投稿, class: :story_new_explanation %><br />
          <%=f.text_area :synopsis, class: 'input_story_new_form' %>
        </div>
        <div class="field form-group">
          <p class="hissu">必須</p>
          <%=f.label :本文, class: :story_new_explanation %><br />
          <%=f.text_area :story, rows: 4, class: 'input_story_new_form' %>
        </div>
        <div class="field form-group">
          <p class="ninni">任意</p>
          <%=f.label :次回予告など、自由に投稿, class: :story_new_explanation %><br />
          <%=f.text_area :notice, class: 'input_story_new_form' %>
        </div>
        
        <%=f.submit "投稿する", class: 'btn btn-primary'%>
      <%end%>
    </div>
    <div class="story_new_side_menu">
      <%=render 'shared/side_menu'%>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<div class="wrapper">
  <div class="story_show_contener">
    <div class="story_show_main_contener">
      <div class="story_show_title_area">
        <h1 class="story_show_title">
          <%=safe_join(@story.title.split("\n"),tag(:br))%>
        </h1>
      </div>

      <div class="story_show_genre_tag_area">

        <div class="story_show_maintitle_area">
          <div class="story_show_maintitle_explanation">
            小説名　：
            <div class="story_show_maintitle">
              <%=link_to maintitle_post_list_path(@maintitle), class: :story_show_maintitle_link do%>
                <%=safe_join(@maintitle.maintitle.split("\n"),tag(:br))%>
              <%end%>
            </div>
          </div>
        </div>
        <div class="story_maintitle_genre_area">
          ジャンル：
          <div class="story_maintitle_genre">
            <%=@maintitle.genre%>
          </div>
        </div>
        <div class="show_review_all_count_area">
          
          <i class="fa fa-thumbs-o-up">
          </i> 
          <i class="review_all_count_area">
            <%if @story_review_count.present?%>
              <%=render 'shared/maintitle_all_review_count'%>
            <%else%>
              <i>
                0
              </i>
            <%end%>
            
          </i>
          　
          <i class="fa fa-commenting-o ">
          </i>
          <i class="comment_count_area">
            <%if @story.comments.present?%>
              <i class="comment_count">
                <%=@story.comments.count%>
              </i>
            <%else%>
              0
            <%end%>
          </i>
        </div>

        <div class="story_show_tag_list_area">
          <p class="story_show_tag_list_title">
            タグ
          </p>
          <div class="story_show_tag_list">
            <%=render 'stories/tag_list', tag_list: @story.tag_list%>
          </div>
        </div>
      </div>

      <div class="story_user_nickname_area">
        
        <div class="story_user_my_image_icon_area">
          <%if @story.user.my_image.present?%>
            <%=image_tag @story.user.my_image.to_s, class: :story_user_my_image_icon%>
          <%else%>
            <%=image_tag "no_avatar.png", class: :story_user_my_image_icon%>
          <%end%>
        </div>
        <h1 class="story_user_nickname">
          著者：
          <%=link_to profile_user_path(@story.user), class: :story_user_nickname_link do%>
            <%=@story.user.nickname%>
          <%end%>
        </h1>

      </div>
      <%if @story.image.present?%>
        <div class="story_show_image_area">
          <%=image_tag @story.image.to_s, class: :story_show_image%>
        </div>
      <%end%>
      <%if @story.synopsis.present?%>
        <div class="story_show_image_explanation_area">
          <%=safe_join(@story.synopsis.split("\n"),tag(:br))%>
        </div>
      <%end%>
      <div class="story_show_story">
        <%=safe_join(@story.story.split("\n"),tag(:br))%>
      </div>

      <%if @story.notice.present?%>
        <div class="story_show_notice_area">
          <%=safe_join(@story.notice.split("\n"),tag(:br))%>
        </div>
      <%end%>

      <div class="previous_next_link_area">
          <div class="previous_link">
            <%if @story.previous%>
              <%=link_to maintitle_story_url(@maintitle, @story.previous), {class:"previous_btn"} do%>
              <i class="fa fa-chevron-left "></i> 
                前の話へ
              <%end%>
            <%end%>
          </div>

          <div class="next_link">
            <%if @story.next%>
              <%=link_to maintitle_story_url(@maintitle, @story.next), {class: "next_btn"} do%>
                次の話へ
                <i class="fa fa-chevron-right"></i> 
              <%end%>
            <%end%>
          </div>
        </div>

      <%if user_signed_in?%>
        <%if @story.user_id == current_user.id%>
          <div class="mystory_new_edit_delete_area">
            <div class="mystory_new_edit_delete">
              <%=link_to new_maintitle_story_path(@maintitle), class: :mystory_new_edit_delete_btn do%>
                続きの話を書く
              <%end%>
              <%=link_to edit_maintitle_story_path(@maintitle, @story), class: "mystory_new_edit_delete_btn" do%>
                編集する
              <%end%>
              <%=link_to maintitle_story_path(@maintitle, @story), method: :delete, data: {confirm: "「#{@story.title}」を削除しますか？"}, class: "mystory_new_edit_delete_btn" do%>
                削除する
              <%end%>
            </div>
          </div>
        <%end%>
        <%if @story.user_id != current_user.id%>

          <div class="like_review_area">
              <%=link_to maintitle_story_like_review_path(@maintitle, @story), method: :post, remote: :true, class: :like_review_btn do%>
                <div class="like_review_link">
                  <div class="like_review", id="<%=@maintitle.id%>">
                    面白かった数だけここをクリック！
                  </div>
                </div>
              <%end%>
            
          </div>
        <%end%>
        
        <%if user_signed_in?%>
          <%if @story.user_id != current_user.id%>
            <div class="show_review_my_count_area">
              あなたの評価：
              <i class="fa fa-thumbs-o-up ">
              </i> 
              <i class="review_my_count_area">
                <%if @review.present?%>
                  <i class="my_count">
                    <%=@review.review%>
                  </i>
                <%else%>
                  <i class="my_count">
                    0
                  </i>
                <%end%>
              </i>
            </div>
            <%=link_to maintitle_story_unlike_review_path(@maintitle, @story), method: :delete, remote: :true, class: :unlike_review_btn do%>
              評価をリセットする
            <%end%>
          <%end%>
        <%end%>
        
        
          
        

        <%if @story.user_id != current_user.id%>
          <div class="story_show_comment_input_area">
            <%=form_with model:[@maintitle, @story, @comment], local:true, id: "new_comment" do |f|%>
              <div>
                <%=f.label :コメントを投稿する, class: :story_show_explanation%>
              </div>
              <div>
                <%=f.text_area :comment, rows: 3, class: :story_show_text_area, name: :comment%>
              </div>
              <%=f.submit "コメントを投稿する", class: 'btn-primary'%>
            <%end%>
          </div>
        <%end%>
      <%else%>
        <div class="story_show_comment_input_area">
          コメントを投稿する場合は
          <%=link_to new_user_session_path, class: :story_show_signup_btn do%>
          ログイン
          <%end%>
          してください
        </div>
      <%end%>

      <h2 class="story_show_comment_title">
        コメント
      </h2>
      <div id="story_show_comment_content">
      <%# 非同期用の要素%>
      </div>
      
      <%if @comments%>
        <%@comments.each do |comment|%>
          <div class="story_show_comment_area", id="story_show_comment_area_<%=comment.id%>">
          
            <%if comment.user.my_image.present?%>
              <div class="show_user_image">
                <%=image_tag "#{comment.user.my_image}", class: :story_comment_user_icon%>
              </div>
            
            <%else%>
              <div class="show_user_image">
                <%=image_tag "no_avatar.png", class: :story_comment_user_icon%>
              </div>
              
            <%end%>
            <div class="story_comment_area">
              <%=comment.user.nickname%>:
              <div class="story_comment_time">
                <%=comment.created_at.strftime('%Y/%m/%d %H:%M')%>
              </div>
            </div>
            <%if user_signed_in?%>
              <%if comment.user == current_user%>
                <%@comment_id = comment.id%>
                <%=link_to maintitle_story_comment_path(@maintitle, @story, comment), method: :delete, remote: :true, class: "story_comment_delete_link", id: "#{@comment_id}" do%>
                  削除
                <%end%>
              <%else%>
              <%end%>
            <%else%>
            <%end%>
            <br />
            <div class="story_user_comment">
              <%=safe_join(comment.comment.split("\n"),tag(:br)) %>
            </div>
          </div>
        <%end%>
        
      <%end%>
      <div class="return_top_page">
        <%=link_to root_path, class: :return_top_page_btn do%>
          トップページに戻る
        <%end%>
      </div>
    </div>
    <%if user_signed_in?%>
      <%if @user != current_user%>
        <%=render 'shared/not_current_side_menu'%>
      <%elsif @user == current_user%>
        <%=render 'shared/side_menu'%>
      <%end%>
    <%else%>
      <%=render 'shared/user_profile_side_menu'%>
    <%end%>
  </div>
</div>

app/views/stories/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        編集が完了しました。
      </h3>
      <%=link_to root_path, class: "destroy_btn" do%>
        ホーム画面に戻る
      <%end%>
      <%=link_to mypagemain_user_path(current_user), class: "destory_btn" do%>
        マイページに戻る
      <%end%>
    </div>
  </div>